<?php

/**
 * @file
 * Installation functions for Compact Forms module.
 */

/**
 * Implements hook_uninstall().
 */
function compact_forms_uninstall() {
  \Drupal::config('compact_forms.settings')
    ->clear('compact_forms_descriptions')
    ->clear('compact_forms_field_size')
    ->clear('compact_forms_ids')
    ->clear('compact_forms_stars')
    ->save();
}

// @todo We need to handle removing the 'compact_forms_colons' value once Migrate API is fully working. 
