<?php

/**
 * @file
 * Compact Forms Drupal module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\compact_forms\Form\CompactForms;

/**
 * Implements hook_help().
 */
function compact_forms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.compact_forms':
      return '<p>' . t('Makes form fields compact by overlaying the field label on top the field itself using jQuery.') . '</p>';
  }
}

/**
 * Implementation of hook_form_alter.
 */
function compact_forms_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#pre_render'][] = [CompactForms::class, 'compact_forms_pre_render'];
}
